import logging
from fastapi import APIRouter, HTTPException, status
from app.models.schemas import SummarizeRequest, SummarizeResponse, ErrorResponse
from app.services.github_service import (
    parse_github_url,
    fetch_repo_metadata,
    fetch_repo_tree,
)
from app.services.content_processor import build_context
from app.services.llm_service import call_llm

router = APIRouter()
logger = logging.getLogger(__name__)


@router.post(
    "/summarize",
    response_model=SummarizeResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Invalid request"},
        404: {"model": ErrorResponse, "description": "Repository not found"},
        500: {"model": ErrorResponse, "description": "Internal server error"},
        502: {"model": ErrorResponse, "description": "LLM service error"},
        503: {"model": ErrorResponse, "description": "Service unavailable"},
    },
    summary="Summarize a GitHub repository",
    description="Accepts a GitHub repository URL and returns a summary generated by an LLM.",
)
async def summarize_repository(request: SummarizeRequest):
    """
    Summarize a GitHub repository.
    
    Accepts a GitHub repository URL and returns:
    - summary: What the project does
    - technologies: List of technologies used
    - structure: How the project is organized
    """
    try:
        # 1. Parse GitHub URL
        logger.info(f"Processing repository: {request.github_url}")
        owner, repo = parse_github_url(request.github_url)
        logger.info(f"Parsed as: {owner}/{repo}")

        # 2. Fetch repository metadata
        logger.info("Fetching repository metadata...")
        metadata = await fetch_repo_metadata(owner, repo)

        if metadata["is_private"]:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={"status": "error", "message": "Repository not found or is private"},
            )

        # 3. Fetch repository tree
        branch = metadata["default_branch"]
        logger.info(f"Fetching repository tree from branch: {branch}")
        tree_items = await fetch_repo_tree(owner, repo, branch)

        if not tree_items:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={"status": "error", "message": "Repository is empty"},
            )

        logger.info(f"Found {len(tree_items)} items in repository")

        # 4. Build context from repository contents
        logger.info("Building context for LLM...")
        context = await build_context(owner, repo, branch, tree_items, metadata)
        logger.info(f"Built context: {len(context)} characters")

        # 5. Call LLM for analysis
        logger.info("Calling LLM for analysis...")
        result = await call_llm(context)
        logger.info("LLM analysis complete")

        # 6. Return structured response
        return SummarizeResponse(
            summary=result["summary"],
            technologies=result["technologies"],
            structure=result["structure"],
        )

    except ValueError as e:
        error_msg = str(e)
        logger.error(f"Validation error: {error_msg}")
        
        # Determine appropriate status code based on error message
        if "not found" in error_msg.lower() or "private" in error_msg.lower():
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={"status": "error", "message": error_msg},
            )
        elif "rate limit" in error_msg.lower():
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail={"status": "error", "message": error_msg},
            )
        elif "timeout" in error_msg.lower():
            raise HTTPException(
                status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                detail={"status": "error", "message": error_msg},
            )
        elif "LLM" in error_msg or "API" in error_msg:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail={"status": "error", "message": error_msg},
            )
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={"status": "error", "message": error_msg},
            )

    except HTTPException:
        raise

    except Exception as e:
        logger.error(f"Unexpected error: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"status": "error", "message": "An unexpected error occurred"},
        )
